### ISSUE TITLE
Artifacts when rendering images

### ISSUE THREAD

**Issue by Avuerro** [vsitzmann/shapenet_renderer#3]
Hi,

I'm trying to render images from the 3D Shapenet models, however the resulting images have artifacts. Initially, I thought this might be solved by implementing backface culling, however, unfortunately the problem still remains. I have tried to follow the instructions as stated in the papers on light field network and continuous scene representations, e.g. radius = 1.3, specularities and shadows disabled and environment lighting energy set to 1.0

These are my results:
![example_1](https://user-images.githubusercontent.com/5059110/165756514-a99bc783-b868-4416-aff4-ecdd648b7003.png)
![example_2](https://user-images.githubusercontent.com/5059110/165759275-3519b0a1-f32a-4452-a7f1-68e0a04447cc.png)

compared to renders from the same model in the SRN Cars dataset 
![example_1](https://user-images.githubusercontent.com/5059110/165759573-17d65e14-62d3-47b1-9d4d-5a8fa52f0c61.png)
![example_2](https://user-images.githubusercontent.com/5059110/165759410-7199fe40-695f-45e4-9636-24faf94fec63.png)

I would greatly appreciate it if you could point me into the right direction to render the images without the artifacts

**Comment by Avuerro** [comment]
Solved, apparently Blender was not able to find the texture files.

**Comment by SeaBird-Go** [comment]
@Avuerro Sorry to bother you. I also encountered this problem, the rendered results are not good as SRN, and the colors also seem not correct. Could you help me how to solved this problem.
![图片](https://user-images.githubusercontent.com/117327481/234754575-37501338-1b27-4b1c-957a-7ee4278c4d0c.png)
![图片](https://user-images.githubusercontent.com/117327481/234754616-184b2dee-47a4-40cd-98bc-cb524381b95e.png)

**Comment by Avuerro** [comment]
@SeaBird-1995 I'm sorry it has been quite a while, I can't remember what I did to solve it and I do not have access to the code I used back then. Unfortunately, I don't think I can be of any help

**Comment by amanikiruga** [comment]
The issue is not textures. I fixed it by making it a larger resolution (512x512 instead of 128x128) then downscaling after rendering to 128x128. It just looked pixelated to me. 
![file](https://github.com/user-attachments/assets/e1e0562a-ab6e-4f03-9dd0-4094a9745801)
![000003](https://github.com/user-attachments/assets/e691004d-b2e0-49b1-bb00-1aff85644c24)
